"""first commit

Revision ID: 55ab8148dfcb
Revises: 
Create Date: 2025-09-26 14:44:41.474822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55ab8148dfcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('enroll', sa.INTEGER(), nullable=True),
    sa.Column('personal_info', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    op.drop_table('place')
    op.alter_column('tickets', 'event',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('tickets_place_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_event_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'places', ['place'], ['id'])
    op.create_foreign_key(None, 'tickets', 'events', ['event'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_event_fkey'), 'tickets', 'event', ['event'], ['id'])
    op.create_foreign_key(op.f('tickets_place_fkey'), 'tickets', 'place', ['place'], ['id'])
    op.alter_column('tickets', 'place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'event',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('place',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('place_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_visitors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('place_pkey'))
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('event_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tickers_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('event_pkey'))
    )
    op.drop_table('places')
    op.drop_table('events')
    # ### end Alembic commands ###
