"""Initial tables

Revision ID: 97841f07c11b
Revises: 
Create Date: 2025-09-26 17:26:25.280665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97841f07c11b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place_name', sa.String(length=128), nullable=False),
    sa.Column('max_visitors', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place', sa.INTEGER(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('event_duration', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['place'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.INTEGER(), nullable=True),
    sa.Column('ticket_status', sa.Enum('available', 'booked', 'sold', 'cancelled', name='ticket_status_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('events')
    op.drop_table('places')
    # ### end Alembic commands ###
