[project]
name = "19-lesson-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "psycopg2-binary>=2.9.10",
]
